<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<PackageId>byo</PackageId>
		<!-- This makes it a .NET tool -->
		<PackAsTool>true</PackAsTool>
		<!-- The command users will run -->
		<ToolCommandName>byo</ToolCommandName>
        <PackageIcon>Icons/sw-logo.png</PackageIcon>

		<!-- NuGet Package Metadata -->
		<Title>BYO CLI</Title>
		<Description>A powerful and flexible CLI tool for developer productivity.</Description>
		<Authors>Leandro Monaco</Authors>
		<Company>Software Worker</Company>
       <PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://byocli.com</PackageProjectUrl>
		<RepositoryUrl>https://github.com/softwareworkercom/byo</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>cli;productivity;software-worker;developer;devex;devops</PackageTags>
	</PropertyGroup>

    <ItemGroup>
      <None Include="..\SoftwareWorker.BYO.Integrations\Icons\sw-logo.png" Link="Icons/sw-logo.png" Pack="true" PackagePath="Icons/">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
	<_Parameter1>ToolCommandName</_Parameter1>
	<_Parameter2>$(ToolCommandName)</_Parameter2>
	</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
     <PackageReference Include="Nerdbank.GitVersioning">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
       <PackageReference Include="Spectre.Console" />
	</ItemGroup>

		<ItemGroup>
			<ProjectReference Include="..\SoftwareWorker.BYO.Core\SoftwareWorker.BYO.Core.csproj" />
			<None Update="version.json">
				<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			</None>
		</ItemGroup>

	</Project>
