<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
		<PackageIcon>Icons\sw-logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.20.0" />
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="GitHub.Copilot.SDK" Version="0.2.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
		<PackageReference Include="Microsoft.Graph" Version="5.103.0" />
		<PackageReference Include="ModelContextProtocol" Version="1.2.0" />
		<PackageReference Include="Nerdbank.GitVersioning" Version="3.10.8-alpha">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="OpenAI" Version="2.10.0" />
		<PackageReference Include="StreamJsonRpc" Version="2.24.84" />
		<PackageReference Include="Spectre.Console" Version="0.55.0" />
		<PackageReference Include="SpreadCheetah" Version="1.27.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
        <PackageReference Include="System.CommandLine" Version="2.0.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SoftwareWorker.BYO.Abstractions\SoftwareWorker.BYO.Abstractions.csproj" />
		<None Update="version.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ProjectExtensions><VisualStudio><UserProperties version_1json__JsonSchema="https://raw.githubusercontent.com/dwp/schemas/main/exchange/publishing-tools/catalogue-entry-schema.json" /></VisualStudio></ProjectExtensions>

</Project>
