<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageIcon>Icons\byo-logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
       <PackageReference Include="CsvHelper" />
		<PackageReference Include="Nerdbank.GitVersioning">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
       <PackageReference Include="Spectre.Console" />
		<PackageReference Include="SpreadCheetah" />
			<PackageReference Include="System.CommandLine" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SoftwareWorker.BYO.Abstractions\SoftwareWorker.BYO.Abstractions.csproj" />
      <Resource Include="C:\GitHub\softwareworkercom\byo\docs\Images\byo-logo.png" Link="Icons\byo-logo.png">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Resource>
		<None Update="version.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ProjectExtensions><VisualStudio><UserProperties version_1json__JsonSchema="https://raw.githubusercontent.com/dwp/schemas/main/exchange/publishing-tools/catalogue-entry-schema.json" /></VisualStudio></ProjectExtensions>

</Project>
