<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
        <PackageIcon>Icons/sw-logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
       <PackageReference Include="CsvHelper" />
       <PackageReference Include="GitHub.Copilot.SDK" />
		<PackageReference Include="Nerdbank.GitVersioning">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Polly" />
		<PackageReference Include="Refit" />
       <PackageReference Include="Spectre.Console" />
		<PackageReference Include="SpreadCheetah" />
			<PackageReference Include="System.CommandLine" />
			<PackageReference Include="System.Security.Cryptography.ProtectedData" />
	</ItemGroup>

	<ItemGroup>
       <None Include="..\SoftwareWorker.BYO.Integrations\Icons\sw-logo.png" Link="Icons/sw-logo.png" Pack="true" PackagePath="Icons/">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="version.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ProjectExtensions><VisualStudio><UserProperties version_1json__JsonSchema="https://raw.githubusercontent.com/dwp/schemas/main/exchange/publishing-tools/catalogue-entry-schema.json" /></VisualStudio></ProjectExtensions>

</Project>
