<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SoftwareWorker.BYO.Core\SoftwareWorker.BYO.Core.csproj" />
    <ProjectReference Include="..\..\src\SoftwareWorker.BYO.Integrations\SoftwareWorker.BYO.Integrations.csproj" />
  </ItemGroup>

</Project>
