<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SoftwareWorker.BYO.Integrations</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageIcon>Icons\sw-logo.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.8-alpha">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Polly" Version="8.6.6" />
    <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
    <PackageReference Include="Refit" Version="10.1.6" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Icons\sw-logo.png" Pack="true">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        <PackagePath>Icons\</PackagePath>
    </None>
  </ItemGroup>

</Project>
