<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SoftwareWorker.BYO.Integrations</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageIcon>Icons\byo-logo.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Polly" />
    <PackageReference Include="Polly.Extensions.Http" />
    <PackageReference Include="Refit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\GitHub\softwareworkercom\byo\docs\Images\byo-logo.png" Link="Icons\byo-logo.png" Pack="true">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        <PackagePath>Icons\</PackagePath>
    </None>
  </ItemGroup>

</Project>
